
package shopbilling;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;


public class LaunchPage extends javax.swing.JFrame 
{

    public LaunchPage() 
    {
        initComponents();
        
        //---------------------------------------------- APP ICON --------------------------------------------------------------
        ImageIcon icon = new ImageIcon("E:\\SIES Practicals\\JAVA SWING\\SHOP_BILLING_PROJECT\\ShopBilling\\src\\shopbilling\\Shopping_cart.png");
        this.setIconImage(icon.getImage());
        
        //ImageIcon bg = new ImageIcon("C:\\KEVIN PROGRAMS\\NETBEANS\\SHOP_BILLING_PROJECT\\ShopBilling\\src\\shopbilling\\Launch_bg.jpg");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        login_label = new javax.swing.JLabel();
        signup_label = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        bglabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Market 77");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(848, 560));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Comic Sans MS", 1, 52)); // NOI18N
        label1.setForeground(new java.awt.Color(236, 8, 45));
        label1.setText("MARKET 77");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 117, -1, -1));

        label2.setFont(new java.awt.Font("DilleniaUPC", 2, 24)); // NOI18N
        label2.setForeground(new java.awt.Color(121, 171, 111));
        label2.setText("Your one stop to shop...");
        jPanel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 260, 40));

        label3.setFont(new java.awt.Font("DilleniaUPC", 2, 18)); // NOI18N
        label3.setForeground(new java.awt.Color(121, 171, 111));
        label3.setText("New User...Sign Up!");
        jPanel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 410, 170, 30));

        login_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopbilling/Login_button.png"))); // NOI18N
        login_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_labelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                login_labelMousePressed(evt);
            }
        });
        jPanel1.add(login_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 110, 50));

        signup_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopbilling/SignUp_button.png"))); // NOI18N
        signup_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signup_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signup_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signup_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signup_labelMouseExited(evt);
            }
        });
        jPanel1.add(signup_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 360, -1, 50));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopbilling/Exit_cross.png"))); // NOI18N
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 50, 50));

        bglabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopbilling/Launch_bg.jpg"))); // NOI18N
        jPanel1.add(bglabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 848, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // -------------------------------------------------- LOGIN MOUSE HOVER --------------------------------------------------------------------------
    private void login_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_labelMouseEntered
        
        login_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopbilling/Login_button_hover.png")));
    }//GEN-LAST:event_login_labelMouseEntered

    private void login_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_labelMouseExited
        login_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopbilling/Login_button.png")));
    }//GEN-LAST:event_login_labelMouseExited
    //----------------------------------------------------------------------------------------------------------------------------------------------
    
    
    
    // ------------------------------------------------ SIGN UP MOUSE HOVER -----------------------------------------------------------------------
    private void signup_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signup_labelMouseEntered
        signup_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopbilling/SignUp_button_hover.png")));
    }//GEN-LAST:event_signup_labelMouseEntered

    private void signup_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signup_labelMouseExited
        signup_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopbilling/SignUp_button.png")));
    }//GEN-LAST:event_signup_labelMouseExited
    //----------------------------------------------------------------------------------------------------------------------------------------------
    
    
    // -------------------------------------------------- CLICKING LOGIN -------------------------------------------------------------------------------
    private void login_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_labelMouseClicked
        new LoginPage().setVisible(true);
    }//GEN-LAST:event_login_labelMouseClicked

    private void login_labelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_labelMousePressed
        ;
    }//GEN-LAST:event_login_labelMousePressed

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        //System.exit(0);
        this.setVisible(false);
    }//GEN-LAST:event_ExitMouseClicked
    //----------------------------------------------------------------------------------------------------------------------------------------------
    
    
    // --------------------------------------------------- CLICKING SIGNUP ------------------------------------------------------------------------
    private void signup_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signup_labelMouseClicked
        new SignUpPage().setVisible(true);
    }//GEN-LAST:event_signup_labelMouseClicked
    // ---------------------------------------------------------------------------------------------------------------------------------------------
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaunchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaunchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaunchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaunchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaunchPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel bglabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel login_label;
    private javax.swing.JLabel signup_label;
    // End of variables declaration//GEN-END:variables
}
