/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopbilling;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;

public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        
        //------------------------------------------------------ IMAGE ICON FOR THE FRAME -----------------------------------------------------------------------------------
        ImageIcon icon = new ImageIcon("E:\\SIES Practicals\\JAVA SWING\\SHOP_BILLING_PROJECT\\ShopBilling\\src\\shopbilling\\Users_main_icon.png");
        this.setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        redPanel = new javax.swing.JPanel();
        Basket = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();
        pinkPanel = new javax.swing.JPanel();
        Username = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        Username_icon = new javax.swing.JLabel();
        Password_icon = new javax.swing.JLabel();
        LetsShopLabel = new javax.swing.JLabel();
        WelcomeLabel = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setMinimumSize(new java.awt.Dimension(848, 560));
        setUndecorated(true);
        setResizable(false);

        redPanel.setBackground(new java.awt.Color(244, 67, 54));
        redPanel.setPreferredSize(new java.awt.Dimension(424, 339));

        Basket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopbilling/Cart_User4.png"))); // NOI18N

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopbilling/Back_arrow.png"))); // NOI18N
        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout redPanelLayout = new javax.swing.GroupLayout(redPanel);
        redPanel.setLayout(redPanelLayout);
        redPanelLayout.setHorizontalGroup(
            redPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(redPanelLayout.createSequentialGroup()
                .addGroup(redPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(redPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(redPanelLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(Basket)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        redPanelLayout.setVerticalGroup(
            redPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(redPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(Basket, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pinkPanel.setBackground(new java.awt.Color(250, 211, 214));
        pinkPanel.setMinimumSize(new java.awt.Dimension(424, 560));
        pinkPanel.setPreferredSize(new java.awt.Dimension(424, 560));
        pinkPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Username.setBackground(new java.awt.Color(250, 211, 214));
        Username.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Username.setForeground(new java.awt.Color(0, 0, 0));
        Username.setText("Username");
        Username.setBorder(null);
        Username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UsernameFocusGained(evt);
            }
        });
        Username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsernameMouseClicked(evt);
            }
        });
        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });
        pinkPanel.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 245, 35));

        Password.setBackground(new java.awt.Color(250, 211, 214));
        Password.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Password.setForeground(new java.awt.Color(0, 0, 0));
        Password.setText("Password");
        Password.setBorder(null);
        Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordFocusGained(evt);
            }
        });
        Password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasswordMouseClicked(evt);
            }
        });
        pinkPanel.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 245, 35));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        pinkPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 195, 244, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        pinkPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 315, 244, 10));

        Username_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopbilling/Username_login.png"))); // NOI18N
        pinkPanel.add(Username_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 50, 50));

        Password_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopbilling/Password_login.png"))); // NOI18N
        pinkPanel.add(Password_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 50, 50));

        LetsShopLabel.setForeground(new java.awt.Color(0, 0, 0));
        LetsShopLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LetsShopLabel.setText("Let's Shop!");
        LetsShopLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        LetsShopLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LetsShopLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LetsShopLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LetsShopLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LetsShopLabelMouseExited(evt);
            }
        });
        pinkPanel.add(LetsShopLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 390, 100, 50));

        WelcomeLabel.setFont(new java.awt.Font("Dialog", 0, 30)); // NOI18N
        WelcomeLabel.setForeground(new java.awt.Color(0, 0, 0));
        WelcomeLabel.setText("Welcome Back!");
        pinkPanel.add(WelcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 210, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(redPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pinkPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(redPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
            .addComponent(pinkPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    
    // --------------------------------------------------------- Lets Shop Hover ---------------------------------------------------------------------
    private void LetsShopLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LetsShopLabelMouseEntered
        LetsShopLabel.setBackground(new java.awt.Color(244,67,54));
        LetsShopLabel.setOpaque(true);
    }//GEN-LAST:event_LetsShopLabelMouseEntered

    
    private void LetsShopLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LetsShopLabelMouseExited
        LetsShopLabel.setBackground(new java.awt.Color(250, 211, 214));
        LetsShopLabel.setOpaque(false);
    }//GEN-LAST:event_LetsShopLabelMouseExited

    private void UsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFocusGained
        
    }//GEN-LAST:event_UsernameFocusGained

    private void PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusGained
        
    }//GEN-LAST:event_PasswordFocusGained
    //----------------------------------------------------------------------------------------------------------------------------------------------
    
    // ----------------------------------------- REMOVING LABELS FROM USERNAME AND PASSWORD WHEN CLICKED --------------------------------------------
    private void UsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsernameMouseClicked
        Username.setText("");
    }//GEN-LAST:event_UsernameMouseClicked

    private void PasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordMouseClicked
        Password.setText("");
    }//GEN-LAST:event_PasswordMouseClicked
    //----------------------------------------------------------------------------------------------------------------------------------------------
    
    
    // --------------------------------------------------- GOING BACK TO THE PREVIOUS PAGE --------------------------------------------------------------
    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_BackMouseClicked
    //----------------------------------------------------------------------------------------------------------------------------------------------
    
    
    // -------------------------------------------------------- AFTER CLICKING LETS SHOP -------------------------------------------------------------
    private void LetsShopLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LetsShopLabelMouseClicked
        
        ImageIcon cs = new ImageIcon("C:\\KEVIN PROGRAMS\\NETBEANS\\SHOP_BILLING_PROJECT\\ShopBilling\\src\\shopbilling\\Confused_smiley.png");
        ImageIcon hs = new ImageIcon("C:\\KEVIN PROGRAMS\\NETBEANS\\SHOP_BILLING_PROJECT\\ShopBilling\\src\\shopbilling\\Happy_smiley.png");
        
        // CHECKING IF USERNAME IS BLANK
        if(Username.getText().trim().isEmpty())
                {
                    
                    JOptionPane.showMessageDialog(null,"Username required!","Oops!",JOptionPane.WARNING_MESSAGE,cs);
                    Username.grabFocus();
                    return;
                    
                }
        
        // CHECKING IF PASSWORD IS BLANK
        if(Password.getText().trim().isEmpty())
                {
                    
                    JOptionPane.showMessageDialog(null,"Password required!","Oops!",JOptionPane.WARNING_MESSAGE,cs);
                    Password.grabFocus();
                    return;
                    
                }
        
        // TAKING THE VALUES FROM TEXTBOXES INTO STRINGS
        String user = Username.getText();  // USERNAME HAS TO ONLY BE IN SMALL LETTERS COZ IM LINKING THE SAME NAME WITH THE DATABASE TABLE NAME .....AND DATABASE TABLE NAMES ARE ALWAYS SMALL LETTERS
        String passwd = Password.getText();
        
        // --------------------------------------------------------- JDBC CONNECTION ------------------------------------------------------------------
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/shop_billing","root","");
            
            String sql = "SELECT uname,pass FROM signup WHERE uname=? and pass=?"; // SQL QUERY FOR CHCEKING IF USERNAME AND PASSWORD ARE SAME AS IN THE DATABASE
            
            PreparedStatement pstmt = con.prepareStatement(sql);
            pstmt.setString(1,user); // GETS THE name IN ?
            pstmt.setString(2,passwd); // GETS THE PASSWORD IN ?
            
            ResultSet rs = pstmt.executeQuery();
            if(rs.next())
            {
                new LaunchPage().dispose(); // CLOSING THE LAUNCH PAGE
                this.setVisible(false);               
                new MainPage(user).setVisible(true); // SENDING THE USERNAME TO THE MAIN PAGE
                
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Wrong Username and Password!","Oops",JOptionPane.WARNING_MESSAGE,cs);
            }
        }
        
        catch(SQLException | ClassNotFoundException e) // EITHER SQL EXCEPTION OR CLASS NOT FOUND EXCEPTION
        {
            System.out.println("ERROR : "+e);
        }
       
       
       
       
    }//GEN-LAST:event_LetsShopLabelMouseClicked


   // ----------------------------------------------------------------------------------------------------------------------------------------------
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LoginPage().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JLabel Basket;
    private javax.swing.JLabel LetsShopLabel;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel Password_icon;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel Username_icon;
    private javax.swing.JLabel WelcomeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel pinkPanel;
    private javax.swing.JPanel redPanel;
    // End of variables declaration//GEN-END:variables
}
