/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopbilling;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;
/**
 *
 * @author nivek
 */
public class MainPage extends javax.swing.JFrame {

   String UserTable; // TO GET USERNAME FROM LOGIN PAGE AND LINK ACCOUNT WITH TABLE IN THE DATABASE WITH THE SAME TABLE NAME
   int count;
    
    public MainPage(String UserFromLogin) {   // TAKING USERNAME FROM LOGIN PAGE
        initComponents();
        
        //---------------------------------------------------------- APP ICON ---------------------------------------------------------------------------------
        ImageIcon icon = new ImageIcon("E:\\SIES Practicals\\JAVA SWING\\SHOP_BILLING_PROJECT\\ShopBilling\\src\\shopbilling\\Shopping_cart.png");
        this.setIconImage(icon.getImage());
        
        Categories.setVisible(false); // MAKING CATEGORIES DISSAPPEAR IN THE START
        
        UserTable = UserFromLogin; // USERNAME FROM LOGIN PAGE
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BasePanel = new javax.swing.JPanel();
        ShoppingCart = new javax.swing.JLabel();
        Market77 = new javax.swing.JLabel();
        Tagline = new javax.swing.JLabel();
        Categories = new javax.swing.JLabel();
        RedCross = new javax.swing.JLabel();
        LogOut = new javax.swing.JLabel();
        CART = new javax.swing.JLabel();
        CARTNUMBER = new javax.swing.JLabel();
        WELCOME = new javax.swing.JLabel();
        LoginPageUsername = new javax.swing.JLabel();
        Underline1 = new javax.swing.JLabel();
        Underline2 = new javax.swing.JLabel();
        FoodBg1 = new javax.swing.JLabel();
        FoodBg2 = new javax.swing.JLabel();
        FoodBg3 = new javax.swing.JLabel();
        FoodBg4 = new javax.swing.JLabel();
        FoodBg5 = new javax.swing.JLabel();
        FoodBg6 = new javax.swing.JLabel();
        FoodBg7 = new javax.swing.JLabel();
        FoodBg8 = new javax.swing.JLabel();
        DailyStaples = new javax.swing.JLabel();
        DairyStuff = new javax.swing.JLabel();
        PackagedFood = new javax.swing.JLabel();
        Vegetables = new javax.swing.JLabel();
        Snacks = new javax.swing.JLabel();
        Fruits = new javax.swing.JLabel();
        PersonalCare = new javax.swing.JLabel();
        Beverages = new javax.swing.JLabel();
        Banner = new javax.swing.JLabel();
        Holder1 = new javax.swing.JLabel();
        Holder2 = new javax.swing.JLabel();
        TableBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MARKET 77");
        setMinimumSize(new java.awt.Dimension(1920, 1036));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1920, 1036));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        BasePanel.setPreferredSize(new java.awt.Dimension(1920, 1030));
        BasePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ShoppingCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopbilling/Shopping_cart128.png"))); // NOI18N
        ShoppingCart.setText("jLabel1");
        BasePanel.add(ShoppingCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 130, 140));

        Market77.setFont(new java.awt.Font("Comic Sans MS", 3, 70)); // NOI18N
        Market77.setForeground(new java.awt.Color(0, 0, 0));
        Market77.setText("MARKET 77");
        BasePanel.add(Market77, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, 420, 80));

        Tagline.setFont(new java.awt.Font("DilleniaUPC", 2, 36)); // NOI18N
        Tagline.setForeground(new java.awt.Color(0, 0, 0));
        Tagline.setText("Your one stop to shop...");
        BasePanel.add(Tagline, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 160, 410, 50));

        Categories.setFont(new java.awt.Font("Comic Sans MS", 3, 70)); // NOI18N
        Categories.setForeground(new java.awt.Color(0, 0, 0));
        Categories.setText("     Categories");
        BasePanel.add(Categories, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 50, 630, 170));

        RedCross.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopbilling/MainPage_cross.png"))); // NOI18N
        RedCross.setText("jLabel8");
        RedCross.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RedCross.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RedCrossMouseClicked(evt);
            }
        });
        BasePanel.add(RedCross, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 70, 70));

        LogOut.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LogOut.setForeground(new java.awt.Color(0, 0, 0));
        LogOut.setText("     Log Out");
        LogOut.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        LogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogOutMouseExited(evt);
            }
        });
        BasePanel.add(LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 15, 130, 50));

        CART.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CART.setForeground(new java.awt.Color(0, 0, 0));
        CART.setText("   Cart");
        CART.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        CART.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CART.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CARTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CARTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CARTMouseExited(evt);
            }
        });
        BasePanel.add(CART, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 15, 75, 50));

        CARTNUMBER.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CARTNUMBER.setForeground(new java.awt.Color(0, 0, 0));
        CARTNUMBER.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CARTNUMBER.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        BasePanel.add(CARTNUMBER, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 15, 60, 50));

        WELCOME.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        WELCOME.setForeground(new java.awt.Color(0, 0, 0));
        WELCOME.setText("Welcome");
        BasePanel.add(WELCOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 30, 140, 50));

        LoginPageUsername.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        LoginPageUsername.setForeground(new java.awt.Color(0, 0, 0));
        LoginPageUsername.setText("      ");
        BasePanel.add(LoginPageUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(1595, 30, 300, 50));

        Underline1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        BasePanel.add(Underline1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 80, 160, -1));

        Underline2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        BasePanel.add(Underline2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1580, 80, 330, -1));

        FoodBg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopbilling/Daily_Staples.png"))); // NOI18N
        FoodBg1.setText("jLabel1");
        BasePanel.add(FoodBg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 260, 260));

        FoodBg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopbilling/Fruits.png"))); // NOI18N
        FoodBg2.setText("jLabel3");
        BasePanel.add(FoodBg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 660, 260, 260));

        FoodBg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopbilling/Dairy_Stuff.png"))); // NOI18N
        FoodBg3.setText("jLabel4");
        BasePanel.add(FoodBg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 260, 260));

        FoodBg4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopbilling/Packaged food.png"))); // NOI18N
        FoodBg4.setText("jLabel5");
        BasePanel.add(FoodBg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 310, 260, 260));

        FoodBg5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopbilling/Beverages.png"))); // NOI18N
        FoodBg5.setText("jLabel6");
        BasePanel.add(FoodBg5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 510, 260, 260));

        FoodBg6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopbilling/Snacks.png"))); // NOI18N
        FoodBg6.setText("jLabel7");
        BasePanel.add(FoodBg6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 570, 260, 260));

        FoodBg7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopbilling/PersonalCare.png"))); // NOI18N
        FoodBg7.setText("jLabel6");
        BasePanel.add(FoodBg7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 640, 260, 260));

        FoodBg8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopbilling/Vegetables.png"))); // NOI18N
        FoodBg8.setText("jLabel6");
        BasePanel.add(FoodBg8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 150, 260, 260));

        DailyStaples.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        DailyStaples.setForeground(new java.awt.Color(0, 0, 0));
        DailyStaples.setText("  Daily Staples");
        DailyStaples.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        DailyStaples.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DailyStaples.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DailyStaplesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DailyStaplesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DailyStaplesMouseExited(evt);
            }
        });
        BasePanel.add(DailyStaples, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 140, 50));

        DairyStuff.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        DairyStuff.setForeground(new java.awt.Color(0, 0, 0));
        DairyStuff.setText("   Dairy Stuff");
        DairyStuff.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        DairyStuff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DairyStuff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DairyStuffMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DairyStuffMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DairyStuffMouseExited(evt);
            }
        });
        BasePanel.add(DairyStuff, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 550, 130, 50));

        PackagedFood.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        PackagedFood.setForeground(new java.awt.Color(0, 0, 0));
        PackagedFood.setText("  Packaged Food");
        PackagedFood.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        PackagedFood.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PackagedFood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PackagedFoodMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PackagedFoodMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PackagedFoodMouseExited(evt);
            }
        });
        BasePanel.add(PackagedFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 580, 160, 50));

        Vegetables.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Vegetables.setForeground(new java.awt.Color(0, 0, 0));
        Vegetables.setText("   Vegetables");
        Vegetables.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        Vegetables.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Vegetables.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VegetablesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VegetablesMouseExited(evt);
            }
        });
        BasePanel.add(Vegetables, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 410, 140, 50));

        Snacks.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Snacks.setForeground(new java.awt.Color(0, 0, 0));
        Snacks.setText("      Snacks");
        Snacks.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        Snacks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Snacks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SnacksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SnacksMouseExited(evt);
            }
        });
        BasePanel.add(Snacks, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 830, 130, 50));

        Fruits.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Fruits.setForeground(new java.awt.Color(0, 0, 0));
        Fruits.setText("       Fruits");
        Fruits.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        Fruits.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Fruits.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FruitsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FruitsMouseExited(evt);
            }
        });
        BasePanel.add(Fruits, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 930, 130, 50));

        PersonalCare.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        PersonalCare.setForeground(new java.awt.Color(0, 0, 0));
        PersonalCare.setText("  Personal Care");
        PersonalCare.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        PersonalCare.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PersonalCare.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PersonalCareMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PersonalCareMouseExited(evt);
            }
        });
        BasePanel.add(PersonalCare, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 910, 150, 50));

        Beverages.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Beverages.setForeground(new java.awt.Color(0, 0, 0));
        Beverages.setText("   Beverages");
        Beverages.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        Beverages.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Beverages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BeveragesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BeveragesMouseExited(evt);
            }
        });
        BasePanel.add(Beverages, new org.netbeans.lib.awtextra.AbsoluteConstraints(1690, 780, 130, 50));

        Banner.setBackground(new java.awt.Color(244, 67, 54));
        Banner.setFont(new java.awt.Font("Comic Sans MS", 3, 70)); // NOI18N
        Banner.setForeground(new java.awt.Color(0, 0, 0));
        Banner.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        Banner.setFocusCycleRoot(true);
        Banner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BannerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BannerMouseExited(evt);
            }
        });
        BasePanel.add(Banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 630, 175));

        Holder1.setBackground(new java.awt.Color(244, 67, 54));
        Holder1.setForeground(new java.awt.Color(244, 67, 54));
        Holder1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        Holder1.setOpaque(true);
        BasePanel.add(Holder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 20, 50));

        Holder2.setBackground(new java.awt.Color(244, 67, 54));
        Holder2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        Holder2.setOpaque(true);
        BasePanel.add(Holder2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 0, 20, 50));

        TableBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopbilling/Table_bg.jpg"))); // NOI18N
        BasePanel.add(TableBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1970, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BasePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1970, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BasePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//---------------------------------------------------------- CLICKING RED CROSS ------------------------------------------------------------------
    private void RedCrossMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RedCrossMouseClicked
        System.exit(0);
    }//GEN-LAST:event_RedCrossMouseClicked
// ----------------------------------------------------------------------------------------------------------------------------------------------

    
    
//--------------------------------------------------------- HOVER OVER ALL BUTTONS ---------------------------------------------------------------
    private void DailyStaplesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DailyStaplesMouseEntered
        DailyStaples.setBackground(new java.awt.Color(244, 67, 54));
        DailyStaples.setOpaque(true);
    }//GEN-LAST:event_DailyStaplesMouseEntered

    private void LogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMouseEntered
        LogOut.setBackground(new java.awt.Color(244, 67, 54));
        LogOut.setOpaque(true);
    }//GEN-LAST:event_LogOutMouseEntered

    private void DairyStuffMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DairyStuffMouseEntered
        DairyStuff.setBackground(new java.awt.Color(244, 67, 54));
        DairyStuff.setOpaque(true);
    }//GEN-LAST:event_DairyStuffMouseEntered

    private void PackagedFoodMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PackagedFoodMouseEntered
        PackagedFood.setBackground(new java.awt.Color(244, 67, 54));
        PackagedFood.setOpaque(true);
    }//GEN-LAST:event_PackagedFoodMouseEntered

    private void VegetablesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VegetablesMouseEntered
        Vegetables.setBackground(new java.awt.Color(244, 67, 54));
        Vegetables.setOpaque(true);
    }//GEN-LAST:event_VegetablesMouseEntered

    private void SnacksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SnacksMouseEntered
        Snacks.setBackground(new java.awt.Color(244, 67, 54));
        Snacks.setOpaque(true);
    }//GEN-LAST:event_SnacksMouseEntered

    private void FruitsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FruitsMouseEntered
        Fruits.setBackground(new java.awt.Color(244, 67, 54));
        Fruits.setOpaque(true);
    }//GEN-LAST:event_FruitsMouseEntered

    private void PersonalCareMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PersonalCareMouseEntered
        PersonalCare.setBackground(new java.awt.Color(244, 67, 54));
        PersonalCare.setOpaque(true);
    }//GEN-LAST:event_PersonalCareMouseEntered

    private void BeveragesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BeveragesMouseEntered
        Beverages.setBackground(new java.awt.Color(244, 67, 54));
        Beverages.setOpaque(true);
    }//GEN-LAST:event_BeveragesMouseEntered

    private void LogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMouseExited
        LogOut.setBackground(new java.awt.Color(244, 68, 54));
        LogOut.setOpaque(false);
    }//GEN-LAST:event_LogOutMouseExited

    private void CARTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CARTMouseEntered
        CART.setBackground(new java.awt.Color(244, 67, 54));
        CART.setOpaque(true);
    }//GEN-LAST:event_CARTMouseEntered

    private void CARTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CARTMouseExited
        CART.setBackground(new java.awt.Color(244, 68, 54));
        CART.setOpaque(false);
    }//GEN-LAST:event_CARTMouseExited

    private void DairyStuffMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DairyStuffMouseExited
        DairyStuff.setBackground(new java.awt.Color(244, 68, 54));
        DairyStuff.setOpaque(false);
    }//GEN-LAST:event_DairyStuffMouseExited

    private void PackagedFoodMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PackagedFoodMouseExited
        PackagedFood.setBackground(new java.awt.Color(244, 68, 54));
        PackagedFood.setOpaque(false);
    }//GEN-LAST:event_PackagedFoodMouseExited

    private void VegetablesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VegetablesMouseExited
        Vegetables.setBackground(new java.awt.Color(244, 68, 54));
        Vegetables.setOpaque(false);
    }//GEN-LAST:event_VegetablesMouseExited

    private void SnacksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SnacksMouseExited
        Snacks.setBackground(new java.awt.Color(244, 68, 54));
        Snacks.setOpaque(false);
    }//GEN-LAST:event_SnacksMouseExited

    private void FruitsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FruitsMouseExited
        Fruits.setBackground(new java.awt.Color(244, 68, 54));
        Fruits.setOpaque(false);
    }//GEN-LAST:event_FruitsMouseExited

    private void PersonalCareMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PersonalCareMouseExited
        PersonalCare.setBackground(new java.awt.Color(244, 68, 54));
        PersonalCare.setOpaque(false);
    }//GEN-LAST:event_PersonalCareMouseExited

    private void BeveragesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BeveragesMouseExited
        Beverages.setBackground(new java.awt.Color(244, 68, 54));
        Beverages.setOpaque(false);
    }//GEN-LAST:event_BeveragesMouseExited

    private void DailyStaplesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DailyStaplesMouseExited
        DailyStaples.setBackground(new java.awt.Color(244, 68, 54));
        DailyStaples.setOpaque(false);
    }//GEN-LAST:event_DailyStaplesMouseExited
    // ----------------------------------------------------------------------------------------------------------------------------------------------





// ----------------------------------------------------------------- HOVER OVER BANNER --------------------------------------------------------------------
    private void BannerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BannerMouseEntered
        Categories.setVisible(true);
        Market77.setVisible(false);
        Tagline.setVisible(false);
        ShoppingCart.setVisible(false);
        Banner.setBackground(new java.awt.Color(244, 67, 54));
        Banner.setOpaque(true);
    }//GEN-LAST:event_BannerMouseEntered

    private void BannerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BannerMouseExited
        Categories.setVisible(false);
        Market77.setVisible(true);
        Tagline.setVisible(true);
        ShoppingCart.setVisible(true);
        Banner.setBackground(new java.awt.Color(244, 68, 54));
        Banner.setOpaque(false);
    }//GEN-LAST:event_BannerMouseExited
// ----------------------------------------------------------------------------------------------------------------------------------------------

    


// ----------------------------------------------------- CLICKING ON DAILY STAPLES AND ON LOG OUT --------------------------------------------------
    private void DailyStaplesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DailyStaplesMouseClicked

        new DailyStaples(UserTable).setVisible(true);
        
        
    }//GEN-LAST:event_DailyStaplesMouseClicked

    private void LogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMouseClicked
        this.setVisible(false);
        new LaunchPage().setVisible(true);
    }//GEN-LAST:event_LogOutMouseClicked
// ----------------------------------------------------------------------------------------------------------------------------------------------
    
    
// ---------------------------------------- ON OPENING MAIN PAGE REFRESHING CART NUMBER FOR THAT PARTICULAR USER-----------------------------------------------------------------------------------   
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        LoginPageUsername.setText(UserTable.toUpperCase()); // TAKING USERNAME FROM LOGIN PAGE AND PUTTING NEXT TO WELCOME
        
        
                    try // JDBC CONNECTION FOR DISPLAYING CART NUMBER ON THE MAIN PAGE BASED ON THE PARTICULAR USER ACCOUNT
                    {
                        Class.forName("com.mysql.jdbc.Driver");
                        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/shop_billing","root","");
                        
                        // FOR DISPLAYING CART NUMBER 
                        String sqlc = "SELECT COUNT(item_name) FROM $tableName"; // WE CANT USE '"+UserTable+"' ......THATS Y WE USE REPLACE
                        String sqlcc = sqlc.replace("$tableName",UserTable);
                        PreparedStatement pstmtc = con.prepareStatement(sqlcc);
                        ResultSet rs = pstmtc.executeQuery();
                        rs.next(); // MOVES POINTER TO FIRST POSITION
                        count = rs.getInt(1); // TAKES THE INTEGER VALUE IN FIRST COLUMN WHICH IS THE COUNT VALUE
                        CARTNUMBER.setText(Integer.toString(count));
                    }    
                    catch(SQLException | ClassNotFoundException e) // EITHER SQL EXCEPTION OR CLASS NOT FOUND EXCEPTION
                    {
                        System.out.println("ERROR : "+e);
                    }
    }//GEN-LAST:event_formWindowOpened
// ----------------------------------------------------------------------------------------------------------------------------------------------
    
  
    
    
// -------------------- WHEN WE SWITCH TO OTHER WINDOWS AND THEN COMEBACK TO THE HOMEPAGE THE CART NUMBER SHOULD GET UPDATED-----------------------------------------------------------------------------------------
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        try // JDBC CONNECTION FOR DISPLAYING CART NUMBER ON THE MAIN PAGE BASED ON THE PARTICULAR USER ACCOUNT
                    {
                        Class.forName("com.mysql.jdbc.Driver");
                        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/shop_billing","root","");
                        
                        // FOR DISPLAYING CART NUMBER 
                        String sqlc = "SELECT COUNT(item_name) FROM $tableName"; // WE CANT USE '"+UserTable+"' ......THATS Y WE USE REPLACE
                        String sqlcc = sqlc.replace("$tableName",UserTable);
                        PreparedStatement pstmtc = con.prepareStatement(sqlcc);
                        ResultSet rs = pstmtc.executeQuery();
                        rs.next(); // MOVES POINTER TO FIRST POSITION
                        count = rs.getInt(1); // TAKES THE INTEGER VALUE IN FIRST COLUMN WHICH IS THE COUNT VALUE
                        CARTNUMBER.setText(Integer.toString(count));
                    }    
                    catch(SQLException | ClassNotFoundException e) // EITHER SQL EXCEPTION OR CLASS NOT FOUND EXCEPTION
                    {
                        System.out.println("ERROR : "+e);
                    }
        
        
    }//GEN-LAST:event_formWindowActivated
// ----------------------------------------------------------------------------------------------------------------------------------------------------
    
// ------------------------------------------------------ CLICKING ON ALL THE TABS ON TOP -----------------------------------------------------------------------------------------        
    
// --------------------------------------------------------- CLICKING ON DAIRY STUFF -----------------------------------------------------------------------------------------    
    private void DairyStuffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DairyStuffMouseClicked
        new DairyStuff(UserTable).setVisible(true);
        
    }//GEN-LAST:event_DairyStuffMouseClicked

// --------------------------------------------------------- CLICKING ON PACKAGED FOOD -----------------------------------------------------------------------------------------    
    private void PackagedFoodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PackagedFoodMouseClicked
        new PackagedFood(UserTable).setVisible(true);
    }//GEN-LAST:event_PackagedFoodMouseClicked

// ------------------------------------------------------------- CLICKING ON CART -----------------------------------------------------------------------------------------            
    private void CARTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CARTMouseClicked
        new CartPage(UserTable).setVisible(true);
    }//GEN-LAST:event_CARTMouseClicked
// ----------------------------------------------------------------------------------------------------------------------------------------------
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage("").setVisible(true); // SENDING JUST A DEFAULT STRING "" INTO THE CONSTRUCTOR
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Banner;
    private javax.swing.JPanel BasePanel;
    private javax.swing.JLabel Beverages;
    private javax.swing.JLabel CART;
    private javax.swing.JLabel CARTNUMBER;
    private javax.swing.JLabel Categories;
    private javax.swing.JLabel DailyStaples;
    private javax.swing.JLabel DairyStuff;
    private javax.swing.JLabel FoodBg1;
    private javax.swing.JLabel FoodBg2;
    private javax.swing.JLabel FoodBg3;
    private javax.swing.JLabel FoodBg4;
    private javax.swing.JLabel FoodBg5;
    private javax.swing.JLabel FoodBg6;
    private javax.swing.JLabel FoodBg7;
    private javax.swing.JLabel FoodBg8;
    private javax.swing.JLabel Fruits;
    private javax.swing.JLabel Holder1;
    private javax.swing.JLabel Holder2;
    private javax.swing.JLabel LogOut;
    private javax.swing.JLabel LoginPageUsername;
    private javax.swing.JLabel Market77;
    private javax.swing.JLabel PackagedFood;
    private javax.swing.JLabel PersonalCare;
    private javax.swing.JLabel RedCross;
    private javax.swing.JLabel ShoppingCart;
    private javax.swing.JLabel Snacks;
    private javax.swing.JLabel TableBg;
    private javax.swing.JLabel Tagline;
    private javax.swing.JLabel Underline1;
    private javax.swing.JLabel Underline2;
    private javax.swing.JLabel Vegetables;
    private javax.swing.JLabel WELCOME;
    // End of variables declaration//GEN-END:variables
}
