/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopbilling;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.*; // FOR DATABASE

public class SignUpPage extends javax.swing.JFrame {

    /**
     * Creates new form SignUpPage
     */
    public SignUpPage() {
        initComponents();
        
        // PUT IMAGE ICON
        ImageIcon icon = new ImageIcon("E:\\SIES Practicals\\JAVA SWING\\SHOP_BILLING_PROJECT\\ShopBilling\\src\\shopbilling\\Users_main_icon.png");
        this.setIconImage(icon.getImage()); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bluePanel = new javax.swing.JPanel();
        RegisterLabel = new javax.swing.JLabel();
        CreateaccountLabel = new javax.swing.JLabel();
        SignUpUserIcon = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();
        pinkPanel = new javax.swing.JPanel();
        Username = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Password = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        Address = new javax.swing.JTextArea();
        Email = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        Mobile = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        Username_icon = new javax.swing.JLabel();
        Password_icon = new javax.swing.JLabel();
        Address_icon = new javax.swing.JLabel();
        Email_icon = new javax.swing.JLabel();
        Mobile_icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sign Up");
        setMinimumSize(new java.awt.Dimension(848, 560));
        setUndecorated(true);

        bluePanel.setBackground(new java.awt.Color(244, 67, 54));
        bluePanel.setPreferredSize(new java.awt.Dimension(424, 339));

        RegisterLabel.setForeground(new java.awt.Color(0, 0, 0));
        RegisterLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegisterLabel.setText("Register!");
        RegisterLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        RegisterLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegisterLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegisterLabelMouseExited(evt);
            }
        });

        CreateaccountLabel.setFont(new java.awt.Font("Dialog", 0, 30)); // NOI18N
        CreateaccountLabel.setForeground(new java.awt.Color(0, 0, 0));
        CreateaccountLabel.setText("Create an account!");

        SignUpUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopbilling/Cart_User2.png"))); // NOI18N
        SignUpUserIcon.setPreferredSize(new java.awt.Dimension(100, 100));

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopbilling/Back_arrow.png"))); // NOI18N
        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bluePanelLayout = new javax.swing.GroupLayout(bluePanel);
        bluePanel.setLayout(bluePanelLayout);
        bluePanelLayout.setHorizontalGroup(
            bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bluePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SignUpUserIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
            .addGroup(bluePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back)
                .addGap(38, 38, 38)
                .addComponent(CreateaccountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bluePanelLayout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addComponent(RegisterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
        );
        bluePanelLayout.setVerticalGroup(
            bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bluePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bluePanelLayout.createSequentialGroup()
                        .addComponent(CreateaccountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(SignUpUserIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(RegisterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bluePanelLayout.createSequentialGroup()
                        .addComponent(Back)
                        .addGap(504, 504, 504))))
        );

        pinkPanel.setBackground(new java.awt.Color(250, 211, 214));
        pinkPanel.setPreferredSize(new java.awt.Dimension(355, 440));
        pinkPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Username.setBackground(new java.awt.Color(250, 211, 214));
        Username.setForeground(new java.awt.Color(0, 0, 0));
        Username.setText("Username (only small letters)");
        Username.setBorder(null);
        Username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UsernameFocusGained(evt);
            }
        });
        Username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsernameMouseClicked(evt);
            }
        });
        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });
        pinkPanel.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 245, 35));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        pinkPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 244, 10));

        Password.setBackground(new java.awt.Color(250, 211, 214));
        Password.setForeground(new java.awt.Color(0, 0, 0));
        Password.setText("Password");
        Password.setBorder(null);
        Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordFocusGained(evt);
            }
        });
        Password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasswordMouseClicked(evt);
            }
        });
        pinkPanel.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 245, 35));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        pinkPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 244, 10));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Address.setBackground(new java.awt.Color(250, 211, 214));
        Address.setColumns(22);
        Address.setForeground(new java.awt.Color(0, 0, 0));
        Address.setLineWrap(true);
        Address.setRows(5);
        Address.setText(" Address");
        Address.setBorder(null);
        Address.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddressMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Address);

        pinkPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 245, 90));

        Email.setBackground(new java.awt.Color(250, 211, 214));
        Email.setForeground(new java.awt.Color(0, 0, 0));
        Email.setText("Email id");
        Email.setBorder(null);
        Email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmailMouseClicked(evt);
            }
        });
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        pinkPanel.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 245, 35));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        pinkPanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 244, 10));

        Mobile.setBackground(new java.awt.Color(250, 211, 214));
        Mobile.setForeground(new java.awt.Color(0, 0, 0));
        Mobile.setText("Mobile no.");
        Mobile.setBorder(null);
        Mobile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MobileMouseClicked(evt);
            }
        });
        Mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MobileActionPerformed(evt);
            }
        });
        pinkPanel.add(Mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 245, 35));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        pinkPanel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 244, 10));

        Username_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopbilling/Username_signup.png"))); // NOI18N
        pinkPanel.add(Username_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, 50));

        Password_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopbilling/Password_signup.png"))); // NOI18N
        pinkPanel.add(Password_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 50, 50));

        Address_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopbilling/Address_signup.png"))); // NOI18N
        pinkPanel.add(Address_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 50, 50));

        Email_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopbilling/Email_signup.png"))); // NOI18N
        pinkPanel.add(Email_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 50, 50));

        Mobile_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopbilling/Mobile_signup.png"))); // NOI18N
        pinkPanel.add(Mobile_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 50, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(bluePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pinkPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bluePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
            .addComponent(pinkPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    // ---------------------------------------------- REMOVING THE LABELS WHEN THEY ARE CLICKED ON --------------------------------------------------------
    private void UsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFocusGained

    }//GEN-LAST:event_UsernameFocusGained

    private void UsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsernameMouseClicked
        Username.setText("");
    }//GEN-LAST:event_UsernameMouseClicked

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    private void PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusGained

    }//GEN-LAST:event_PasswordFocusGained

    private void PasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordMouseClicked
        Password.setText("");
    }//GEN-LAST:event_PasswordMouseClicked

    private void AddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddressMouseClicked
        Address.setText("");
    }//GEN-LAST:event_AddressMouseClicked

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void EmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmailMouseClicked
        Email.setText("");
    }//GEN-LAST:event_EmailMouseClicked

    private void MobileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MobileMouseClicked
        Mobile.setText("");
    }//GEN-LAST:event_MobileMouseClicked

    private void MobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MobileActionPerformed
    //----------------------------------------------------------------------------------------------------------------------------------------------
    
    
    // --------------------------------------------------------- REGISTER LABEL HOVER ---------------------------------------------------------------
    private void RegisterLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterLabelMouseEntered
        RegisterLabel.setBackground(new java.awt.Color(250,211,214));
        RegisterLabel.setOpaque(true);
    }//GEN-LAST:event_RegisterLabelMouseEntered

    private void RegisterLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterLabelMouseExited
        RegisterLabel.setBackground(new java.awt.Color(211,250,247));
        RegisterLabel.setOpaque(false);
    }//GEN-LAST:event_RegisterLabelMouseExited
    //----------------------------------------------------------------------------------------------------------------------------------------------
    
    
    
    // ---------------------------------------------------------------- BACK CLICK ------------------------------------------------------------------
    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_BackMouseClicked
    //----------------------------------------------------------------------------------------------------------------------------------------------
    
    
    
    // ------------------------------------------------------------ ON CLICKING REGISTER -----------------------------------------------------------
    private void RegisterLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterLabelMouseClicked
        
        ImageIcon cs = new ImageIcon("C:\\KEVIN PROGRAMS\\NETBEANS\\SHOP_BILLING_PROJECT\\ShopBilling\\src\\shopbilling\\Confused_smiley.png");
        ImageIcon hs = new ImageIcon("C:\\KEVIN PROGRAMS\\NETBEANS\\SHOP_BILLING_PROJECT\\ShopBilling\\src\\shopbilling\\Happy_smiley.png");
        
        // CHECKING IF USERNAME IS BLANK
        if(Username.getText().trim().isEmpty())
                {
                    
                    JOptionPane.showMessageDialog(null,"Please enter Username!","Oops!",JOptionPane.WARNING_MESSAGE,cs);
                    Username.grabFocus();
                    return;
                    
                }
        
//        // CHECKING SO THAT USERNAME SHOULD ONLY BE SMALL LETTERS SO THAT WE CAN CREATE A TABLE IN DATABASE
//        if(Username.getText().matches("[A-Z0-9]"))
//                {
//                    
//                    JOptionPane.showMessageDialog(null,"Username should contain only small letters!","Oops!",JOptionPane.WARNING_MESSAGE,cs);
//                    Username.grabFocus();
//                    return;
//                    
//                }
        
        
        // CHECKING IF PASSWORD IS BLANK
        if(Password.getText().trim().isEmpty())
                {
                    
                    JOptionPane.showMessageDialog(null,"Please enter Password!","Oops!",JOptionPane.WARNING_MESSAGE,cs);
                    Password.grabFocus();
                    return;
                    
                }
        
        // CHECKING IF ADDRESS IS BLANK
        if(Address.getText().trim().isEmpty())
                {
                    
                    JOptionPane.showMessageDialog(null,"Please enter Address!","Oops!",JOptionPane.WARNING_MESSAGE,cs);
                    Address.grabFocus();
                    return;
                    
                }
        
        // CHECKING IF EMAIL IS BLANK
        if(Email.getText().trim().isEmpty())
                {
                   
                    JOptionPane.showMessageDialog(null,"Please enter Email!","Oops!",JOptionPane.WARNING_MESSAGE,cs);
                    Email.grabFocus();
                    return;
                    
                }
        
        // CHECKING IF MOBILE NO. IS BLANK
        if(Mobile.getText().trim().isEmpty())
                {
                    
                    JOptionPane.showMessageDialog(null,"Please enter Mobile No.!","Oops!",JOptionPane.WARNING_MESSAGE,cs);
                    Mobile.grabFocus();
                    return;
                    
                }
        
        // CHECKING MOBILE NO. SHOULD ONLY HAVE 10 NUMBERS
        if(Mobile.getText().length()!=10)
        {
           
                    JOptionPane.showMessageDialog(null,"Enter exactly 10 numbers!","Oops!",JOptionPane.WARNING_MESSAGE,cs);
                    Mobile.grabFocus();
                    return;
        }
        
        
        // TAKING THE VALUES FROM TEXTBOXES INTO STRINGS
        String user = Username.getText().toLowerCase(); // USERNAME HAS TO ONLY BE IN SMALL LETTERS COZ IM LINKING THE SAME NAME WITH THE DATABASE TABLE NAME .....AND DATABASE TABLE NAMES ARE ALWAYS SMALL LETTERS
        String passwd = Password.getText();
        String add = Address.getText();
        String eid = Email.getText();
        String mno = Mobile.getText();
        
        
        // -------------------------------------------------- JDBC CONNECTION -------------------------------------------------------------------------
         try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/shop_billing","root","");
            
            String sql = "INSERT INTO signup(uname,pass,address,email,mobile) VALUES(?,?,?,?,?)"; // SQL QUERY FOR INSERTING VALUES INSIDE SIGN UP DATABASE
            
            PreparedStatement pstmt = con.prepareStatement(sql);
            
            pstmt.setString(1,user);
            pstmt.setString(2,passwd);
            pstmt.setString(3,add);
            pstmt.setString(4,eid);
            pstmt.setString(5,mno);
            
            int count = pstmt.executeUpdate();
            
            if(count==0)
            {
                JOptionPane.showMessageDialog(null,"Your account already exists!","Oops",JOptionPane.WARNING_MESSAGE,cs);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Account created successfully!","Yaaay!",JOptionPane.WARNING_MESSAGE,hs);
                this.setVisible(false);
            }
            
        }
         
         catch(SQLException | ClassNotFoundException e) // EITHER SQL EXCEPTION OR CLASS NOT FOUND EXCEPTION
        {
            System.out.println("ERROR : "+e);
        }
    
    }//GEN-LAST:event_RegisterLabelMouseClicked

    // ---------------------------------------------------------------------------------------------------------------------------------------------
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SignUpPage().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Address;
    private javax.swing.JLabel Address_icon;
    private javax.swing.JLabel Back;
    private javax.swing.JLabel CreateaccountLabel;
    private javax.swing.JTextField Email;
    private javax.swing.JLabel Email_icon;
    private javax.swing.JTextField Mobile;
    private javax.swing.JLabel Mobile_icon;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel Password_icon;
    private javax.swing.JLabel RegisterLabel;
    private javax.swing.JLabel SignUpUserIcon;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel Username_icon;
    private javax.swing.JPanel bluePanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel pinkPanel;
    // End of variables declaration//GEN-END:variables
}
